version: '3.2'

services:
  apicersa:
    restart: always
    volumes:
       - ./public:/srv/app/public
       - ./storage:/srv/app/storage
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8000:3000
      - 8001:3001
